AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyECSFargateCluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MyTaskDefinition
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::898035109227:role/tc-instance-role
      ContainerDefinitions:
        - Name: MyContainer
          Image: 898035109227.dkr.ecr.us-east-1.amazonaws.com/tomcat:custom
          PortMappings:
            - ContainerPort: 8081
              Protocol: tcp

  Service:
    Type: AWS::ECS::Service
    DependsOn: ECSCluster
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: MyECSService
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-0fb466cba99fc96c5 
          SecurityGroups:
            - sg-0125dd265256f113d
          AssignPublicIp: ENABLED
